FROM vipintm/xelatex

# RUN apt-get update && \
#     apt-get install --yes --no-install-recommends \
#     texlive-lang-cyrillic texlive-lang-german \
#     apt-get autoclean && apt-get --purge --yes autoremove && \
#     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
