pipeline {
    agent {
        dockerfile {
            filename '.pws/Dockerfile'
        }
    }
    stages {
        stage('build') {
            steps {
                sh 'git clean -xffd'
                sh 'xelatex index.tex'
                archiveArtifacts artifacts: '*.pdf'
            }
        }
    }
}
