pipeline {
    agent {
        dockerfile {
            label 'linux && docker'
            filename '.pws/Dockerfile'
        }
    }
    stages {
        stage('build') {
            steps {
                sh 'git clean -xffd'
                // Run 3 times to recalc output PDF page layout
                sh 'xelatex de-konspekt.tex'
                sh 'xelatex de-konspekt.tex'
                sh 'xelatex de-konspekt.tex'
                archiveArtifacts artifacts: '*.pdf'
            }
        }
    }
}
